project:
  type: website

website:
  title: "Will Shelley"
  favicon: "assets/will_head.jpg"
  navbar:
    left:
      - text: "Home"
        href: index.html
      - text: "Projects"
        href: projects.html
      - text: "Resume"
        href: resume.html
      - text: "About"
        href: about.html
  page-footer:
    left: "© 2025 Will Shelley"
    right: "Built with [Quarto](https://quarto.org)"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true